#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-only
#
# Copyright (C) 2026 Corey Pennycuff
#
# This file is part of Ghoti.io Unicode.
#
# Ghoti.io Unicode is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License version 3 as
# published by the Free Software Foundation.
"""Differential: this library against CPython's unicodedata module.

A third opinion, and a genuinely independent one - CPython's tables are
generated by CPython's own tooling from the same files, which is exactly the
kind of second source worth having: it can agree with us and be wrong only if
the Consortium's data is wrong, and it disagrees the moment either of us has a
parsing bug.

**An oracle's Unicode version is the pin that matters, and it used to be
whatever this machine had.** The reference here was `import unicodedata` in this
tool's own process, which is the one shape of oracle that cannot be pinned at
all: Debian 13 gives CPython 3.13 and UCD 15.1 where these tables are 17.0.0,
and the entire triage list this header used to carry was that skew rather than
any defect. The reference is now `unicodedata_ask.py` run through
`oracle_env.command()`, in an image pinned by digest in
`containers/IMAGES`.

Two pins, and the difference between them is the point:

  * **python**, a released CPython on UCD 16.0.0. The gating pin, and still
    behind these tables, so this is advisory against it.
  * **python-next**, a release candidate on UCD **17.0.0** - an exact match with
    `tools/ucd/UCD_VERSION`. Against a reference that matches, there is no skew
    left to excuse a disagreement, and `--strict` says so with its exit status.

Measured 2026-09-24, and these are the numbers the two pins give:

    make check-oracle-unicodedata           UCD 16.0.0   2 differed, 6153 ours only
    make check-oracle-unicodedata-strict    UCD 17.0.0   0 differed, 0 ours only

**What the matching pin retired.** Against UCD 15.1 this header carried a
five-category triage of 198 differences and 6,153 "ours only". At 16.0.0 that is
down to two differences, and at 17.0.0 to none:

  * `General_Category` U+0295 `Ll` to `Lo` and `Numeric_Value` U+5146 a million
    to a million million - the two Consortium decisions that land in 17.0 rather
    than 16.0, and the whole of what the 16.0 pin still reports;
  * `Bidi_Class` 6, `East_Asian_Width` 188 and `Bidi_Mirrored` 1 - all 16.0
    changes, and all gone at the 16.0 pin;
  * `Numeric_Value` 8 "ours only", cuneiform signs given values after 15.1, and
    `Name` 6,145 "ours only", the Tangut ideographs. CPython 3.15 computes the
    Tangut algorithmic names, so these are gone at 17.0.0 too - they were the
    oracle's limitation, exactly as the earlier triage said.

**DerivedAge excludes only what is newer than the oracle**, and the first
version of this excluded every unassigned codepoint as well - 814,664 of them,
73% of the codespace, reported as "not comparable". That was wrong in a way that
read as caution: assignments are never withdrawn, so a codepoint unassigned in
17.0.0 is unassigned in every earlier version, and both sides have an answer for
it. Comparing them is what took the strict run from 2.2 million comparisons to
7,947,413, and it puts the end of every run in the trie under the oracle's eye -
a last range one codepoint too long is the defect this differential is best
placed to catch and was structurally unable to see. The Hangul deletion below
added the remaining 11,172, so the strict run makes 7,958,585 comparisons today
and reports nothing not comparable at all.

**The 11,172 Hangul syllables are compared, and used not to be.** This tool
skipped them for `Decomposition_Type` on the grounds that
`unicodedata.decomposition()` returns only the mapping `UnicodeData.txt`
records, and a Hangul syllable's is arithmetic and recorded nowhere. That was
measured against this machine's `python3` and is false on both pins: 3.14.7 and
3.15.0rc2 both answer `1100 1161` for U+AC00, and so does 3.13.15 - the change
is a CPython patch release, not a version of the UCD, which is why the version
field of `containers/IMAGES` cannot express it (3.13.5 answers `''` and 3.13.15
does not, on the same `unidata_version`). Both pins therefore resolve
`canonical` for all 11,172, which is what `DerivedDecompositionType.txt` and
this library say.

The exclusion is deleted rather than made conditional on a probe of the
reference. A probe would keep the skip correct and make it invisible: the strict
gate would withdraw 11,172 comparisons and still print `ok` if some later
CPython stopped answering, which is the shape a gate must not have. Deleted, the
same regression fails the gate. A host-mode run on an interpreter old enough to
lack it reports 11,172 differences, and that is the reading it is entitled to -
host mode is unpinned, says so in the line it prints, and is advisory.

Every skip is counted under the reason for it, because one figure covering
several reasons means something different against a matching pin while printing
the same.

What is compared: General_Category, Canonical_Combining_Class, Bidi_Class,
East_Asian_Width, Bidi_Mirrored, Decomposition_Type, Numeric_Value and the
character names. Not the segmentation, normalisation or bidi algorithms:
`unicodedata` exposes none of them, and the Consortium's own conformance files
gate those in `make test`.

The library's answers come from the test binaries' dump modes -
`GUNI_SWEEP_DUMP` and `GUNI_NAME_DUMP` - rather than from a driver of its own,
because a differential wants the library's answers as text and a test binary
already links the library.

Usage:
    make test                                   # build the binaries first
    make check-oracle-unicodedata               # the released pin, advisory
    make check-oracle-unicodedata-strict        # the matching pin, and it fails
    tools/oracle/unicodedata_diff.py --property Bidi_Class

It needs the fetched UCD, for `DerivedAge.txt`: run `tools/ucd/fetch.sh` first.
That is the second reason neither target is in `TEST_GATES`, the first being
that a differential needs a container engine and `make test` must not.

Exit status is 1 on any disagreement, and 1 if it could compare nothing.
"""

import argparse
import os
import subprocess
import sys
from fractions import Fraction

MAX_CODEPOINT = 0x10FFFF

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))

sys.path.insert(0, HERE)
import oracle_env


def version_tuple(text):
    parts = [int(part) for part in text.split(".")]
    while len(parts) < 3:
        parts.append(0)
    return tuple(parts[:3])


def read_derived_age(ucd_dir):
    """Codepoint to the Unicode version that assigned it."""
    ages = [None] * (MAX_CODEPOINT + 1)
    with open(os.path.join(ucd_dir, "DerivedAge.txt"), encoding="utf-8") as handle:
        for line in handle:
            body = line.split("#", 1)[0].strip()
            if not body:
                continue
            first, _sep, value = (field.strip() for field in body.partition(";"))
            halves = first.split("..")
            low = int(halves[0], 16)
            high = int(halves[-1], 16)
            age = version_tuple(value)
            for cp in range(low, min(high, MAX_CODEPOINT) + 1):
                ages[cp] = age
    return ages


def read_value_aliases(ucd_dir):
    """{property: {long name: short name}}, for the codes unicodedata returns."""
    out = {}
    with open(os.path.join(ucd_dir, "PropertyValueAliases.txt"),
              encoding="utf-8") as handle:
        for line in handle:
            body = line.split("#", 1)[0].strip()
            if not body:
                continue
            fields = [field.strip() for field in body.split(";")]
            if fields[0] == "ccc":
                continue
            if len(fields) >= 3:
                out.setdefault(fields[0], {})[fields[2]] = fields[1]
    return out


def dump_property(binary, name):
    """The library's answer for one property, as (first, last, value) runs."""
    environment = dict(os.environ)
    environment["GUNI_SWEEP_DUMP"] = name
    environment.setdefault("GUNI_TEST_DATA", os.path.join(ROOT, "tests", "data"))
    result = subprocess.run([binary], env=environment, capture_output=True,
                            text=True, check=True)
    runs = []
    for line in result.stdout.splitlines():
        bounds, _space, value = line.partition(" ")
        low, _dots, high = bounds.partition("..")
        runs.append((int(low, 16), int(high, 16), value))
    return runs


def dump_names(binary):
    """The library's names, as {codepoint: name}."""
    environment = dict(os.environ)
    environment["GUNI_NAME_DUMP"] = "1"
    result = subprocess.run([binary], env=environment, capture_output=True,
                            text=True, check=True)
    out = {}
    for line in result.stdout.splitlines():
        code, _space, name = line.partition(" ")
        out[int(code, 16)] = name
    return out


ORACLE = "python"


def ask_oracle(properties, scratch=None):
    """One process, every property, run-encoded. Returns (UCD version, runs).

    The reference used to be `import unicodedata` in this process, which made
    "the reference" whichever interpreter ran the tool - the one pin that cannot
    be written down anywhere. It is now `tools/oracle/unicodedata_ask.py`, run
    through `oracle_env.command()` so that it lands in the image pinned by
    digest in `containers/IMAGES`.

    One process for the whole run, not one per property and emphatically not one
    per codepoint. Starting the engine costs about 200ms, paid once.

    The frame header carries the property's name and an exact line count, and
    both are checked. A parent that loses sync with this child would not notice
    otherwise, and there is a live way to lose it - the engine on this machine
    writes a banner to stderr on every invocation, so a driver that merged the
    streams would read it as an answer.
    """
    requests = ["version"] + list(properties)
    argv = oracle_env.command(ORACLE, ["python3",
        os.path.join(HERE, "unicodedata_ask.py")], scratch=scratch)
    child = subprocess.Popen(argv, stdin=subprocess.PIPE,
        stdout=subprocess.PIPE, text=True)
    out, _ = child.communicate("\n".join(requests) + "\n")
    if child.returncode != 0:
        raise SystemExit("the oracle driver exited %d" % child.returncode)

    lines = out.splitlines()
    at = 0
    answers = {}
    for name in requests:
        if at >= len(lines):
            raise SystemExit("the oracle stopped answering before %s" % name)
        head = lines[at].split("\t")
        at += 1
        if len(head) != 2 or head[0] != name:
            raise SystemExit("asked for %s and the frame says %r"
                             % (name, lines[at - 1]))
        count = int(head[1])
        body, at = lines[at:at + count], at + count
        if len(body) != count:
            raise SystemExit("%s: the frame promised %d lines and %d arrived"
                             % (name, count, len(body)))
        answers[name] = body
    if at != len(lines):
        raise SystemExit("%d lines arrived after the last frame" % (len(lines) - at))

    unidata = answers.pop("version")[0].split("\t")[1]
    runs = {}
    for name, body in answers.items():
        table = []
        for line in body:
            bounds, _tab, value = line.partition("\t")
            low, dots, high = bounds.partition("..")
            first = int(low, 16)
            table.append((first, int(high, 16) if dots else first,
                          None if value == "-" else value))
        runs[name] = table
    return unidata, runs


def expand(table):
    """A run table as one value per codepoint, for a lookup by codepoint.

    Both sides of every comparison here are run tables, but our side is walked
    run by run and the oracle's has to be read at an arbitrary codepoint inside
    one of ours, so one of the two has to be flattened. One property at a time,
    which is where the memory goes.
    """
    out = [None] * (MAX_CODEPOINT + 1)
    for first, last, value in table:
        for cp in range(first, last + 1):
            out[cp] = value
    return out


class Comparison:
    """One property's tally, in four buckets.

    Four rather than two, because "disagreed" lumps together three different
    situations and only one of them is a defect:

      * **differed**: both sides have an answer and they are not the same. A
        defect, or the Consortium changing its mind between the two versions.
      * **ours only**: this library has an answer and the oracle has none. For
        names that is usually the oracle's limitation - CPython computes the CJK
        and Hangul algorithmic names and not the Tangut ones - and for a value
        it is usually newer data.
      * **theirs only**: the oracle has an answer and we do not, which is the
        one that would most likely be ours.
      * **not comparable**: the codepoint is newer than the oracle's UCD.
    """

    def __init__(self, name):
        self.name = name
        self.agreed = 0
        self.differed = 0
        self.ours_only = 0
        self.theirs_only = 0
        self.incomparable = 0
        self.reasons = {}
        self.examples = []

    def skip(self, reason):
        """Not compared, and *why*.

        One number for this used to be enough, because there was only ever one
        reason: the oracle was two releases behind and most of the codespace was
        newer than it. Against a pin that matches the library's UCD that reason
        disappears and the others do not, and a single figure then means
        something quite different while printing the same. A reader cannot tell
        "the reference does not reach here" from "nothing is here" without being
        told which.
        """
        self.incomparable += 1
        self.reasons[reason] = self.reasons.get(reason, 0) + 1

    def check(self, cp, ours, theirs):
        if ours == theirs:
            self.agreed += 1
            return
        if theirs is None:
            self.ours_only += 1
        elif ours is None:
            self.theirs_only += 1
        else:
            self.differed += 1
        if len(self.examples) < 4:
            self.examples.append((cp, ours, theirs))

    @property
    def compared(self):
        return self.agreed + self.differed + self.ours_only + self.theirs_only

    def report(self):
        status = "ok" if self.differed == 0 and self.theirs_only == 0 else "differs"
        print("  %-26s %8d agreed %6d differed %6d ours only %6d theirs only"
              "  %9d not comparable  %s"
              % (self.name, self.agreed, self.differed, self.ours_only,
                 self.theirs_only, self.incomparable, status))
        if self.reasons:
            print("      not comparable: %s"
                  % ", ".join("%d %s" % (count, reason) for reason, count
                              in sorted(self.reasons.items(),
                                        key=lambda pair: -pair[1])))
        for cp, ours, theirs in self.examples:
            print("      U+%04X: ours %r, unicodedata %r" % (cp, ours, theirs))


def main(argv):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--build", default=os.path.join(ROOT, "build", "linux",
                                                        "release", "apps"),
                        help="where the test binaries are")
    parser.add_argument("--ucd", help="the unpacked UCD directory")
    parser.add_argument("--property", action="append",
                        help="compare only these (may be repeated)")
    parser.add_argument("--strict", action="store_true",
                        help="exit 1 on any disagreement, for an oracle whose "
                             "UCD version matches the library's")
    args = parser.parse_args(argv[1:])

    version = open(os.path.join(ROOT, "tools", "ucd", "UCD_VERSION"),
                   encoding="utf-8").read().strip()
    ucd_dir = args.ucd or os.path.join(ROOT, "third_party", "ucd", version)
    if not os.path.isdir(ucd_dir):
        raise SystemExit("%s does not exist; run tools/ucd/fetch.sh - this "
                         "differential needs DerivedAge.txt to know what is "
                         "comparable" % ucd_dir)

    sweep = os.path.join(args.build, "testSweep")
    names_binary = os.path.join(args.build, "testName")
    for binary in (sweep, names_binary):
        if not os.path.exists(binary):
            raise SystemExit("%s is not built; run make test first" % binary)

    order = ["General_Category", "Bidi_Class", "East_Asian_Width",
             "Canonical_Combining_Class", "Bidi_Mirrored", "Decomposition_Type",
             "Numeric_Value", "Name"]
    wanted = args.property
    if wanted:
        unknown = [name for name in wanted if name not in order]
        if unknown:
            raise SystemExit("not a property this compares: %s"
                             % ", ".join(unknown))
    asking = [name for name in order if not wanted or name in wanted]

    unidata, oracle = ask_oracle(asking)
    oracle_version = version_tuple(unidata)
    print("reference: unicodedata %s" % unidata)
    print("library: UCD %s" % version)
    if oracle_version < version_tuple(version):
        print("the oracle is behind, so every codepoint assigned after %s is "
              "not comparable" % unidata)
    print()

    ages = read_derived_age(ucd_dir)
    aliases = read_value_aliases(ucd_dir)

    def too_new(cp):
        """The one reason DerivedAge can give for not comparing a codepoint.

        The first version of this also excluded every codepoint with no age at
        all - 814,664 of them, unassigned - and that was wrong in a way worth
        recording, because it read as caution. Assignments are never withdrawn,
        so a codepoint unassigned in 17.0.0 is unassigned in every earlier
        version too, and *both sides have an answer for it*: `Cn`, width `N`,
        combining class 0, no name. Excluding them left the differential unable
        to see the one defect it is best placed to catch - a run table whose last
        range runs one codepoint past the end of its block - across 73% of the
        codespace, while reporting the omission as "not comparable".
        """
        age = ages[cp]
        return age is not None and age > oracle_version

    # (property, the key PropertyValueAliases uses)
    scalar = [
        ("General_Category", "gc"),
        ("Bidi_Class", "bc"),
        ("East_Asian_Width", "ea"),
    ]
    results = []

    for name, key in scalar:
        if name not in asking:
            continue
        tally = Comparison(name)
        short_of = aliases.get(key, {})
        theirs_of = expand(oracle[name])
        for low, high, value in dump_property(sweep, name):
            ours = short_of.get(value, value)
            for cp in range(low, high + 1):
                if too_new(cp):
                    tally.skip("newer than the oracle")
                    continue
                theirs = theirs_of[cp]
                if theirs is None:
                    # The oracle declined: unicodedata answers "" for a
                    # codepoint it has no data for, which is not a disagreement
                    # about the value.
                    tally.skip("no oracle data")
                    continue
                tally.check(cp, ours, theirs)
        results.append(tally)

    if "Canonical_Combining_Class" in asking:
        tally = Comparison("Canonical_Combining_Class")
        theirs_of = expand(oracle["Canonical_Combining_Class"])
        for low, high, value in dump_property(sweep, "Canonical_Combining_Class"):
            ours = int(value)
            for cp in range(low, high + 1):
                if too_new(cp):
                    tally.skip("newer than the oracle")
                    continue
                tally.check(cp, ours, int(theirs_of[cp]))
        results.append(tally)

    if "Bidi_Mirrored" in asking:
        tally = Comparison("Bidi_Mirrored")
        theirs_of = expand(oracle["Bidi_Mirrored"])
        for low, high, value in dump_property(sweep, "Bidi_Mirrored"):
            ours = value == "Yes"
            for cp in range(low, high + 1):
                if too_new(cp):
                    tally.skip("newer than the oracle")
                    continue
                tally.check(cp, ours, theirs_of[cp] == "Y")
        results.append(tally)

    if "Decomposition_Type" in asking:
        tally = Comparison("Decomposition_Type")
        theirs_of = expand(oracle["Decomposition_Type"])
        for low, high, value in dump_property(sweep, "Decomposition_Type"):
            # The long name, lowercased: unicodedata returns the UCD's own tag
            # text - "noBreak", "compat", "super" - and the long alias is that
            # text. Mapping to the short alias instead compared "nb" with
            # "nobreak" and reported every decomposable character.
            ours = value.lower()
            for cp in range(low, high + 1):
                if too_new(cp):
                    tally.skip("newer than the oracle")
                    continue
                # The driver does the mechanical half - reading the tag out of
                # `<noBreak> 0020`, and answering "canonical" where there is no
                # tag and "none" where there is no mapping. The first version of
                # this compared against the short alias "can" and reported all
                # 13,233 canonically decomposable characters as disagreements,
                # which is what an oracle that is wrong looks like from the
                # outside, and is why the triage is in this file.
                tally.check(cp, ours, theirs_of[cp])
        results.append(tally)

    if "Numeric_Value" in asking:
        tally = Comparison("Numeric_Value")
        theirs_of = expand(oracle["Numeric_Value"])
        for low, high, value in dump_property(sweep, "Numeric_Value"):
            ours = None if value == "None" else Fraction(value)
            for cp in range(low, high + 1):
                if too_new(cp):
                    tally.skip("newer than the oracle")
                    continue
                # A declined answer here is a real one - "this character has no
                # numeric value" - unlike Bidi_Class above, where it means the
                # oracle's tables do not reach the codepoint. Compared as
                # rationals and not as floats: the UCD has 1/3, and a float
                # comparison of that is a coin toss.
                text = theirs_of[cp]
                theirs = None if text is None else Fraction(text)
                tally.check(cp, ours, theirs)
        results.append(tally)

    if "Name" in asking:
        tally = Comparison("Name")
        ours_names = dump_names(names_binary)
        theirs_of = expand(oracle["Name"])
        for cp in range(MAX_CODEPOINT + 1):
            if too_new(cp):
                tally.skip("newer than the oracle")
                continue
            # A declined answer is again a real one: the codepoint has no name.
            theirs = theirs_of[cp]
            ours = ours_names.get(cp)
            if ours is None and theirs is None:
                continue  # neither names it; nothing to compare
            tally.check(cp, ours, theirs)
        results.append(tally)

    for tally in results:
        tally.report()

    compared = sum(tally.compared for tally in results)
    differed = sum(tally.differed for tally in results)
    ours_only = sum(tally.ours_only for tally in results)
    theirs_only = sum(tally.theirs_only for tally in results)
    print()
    if compared == 0:
        print("nothing was compared, which is not a pass")
        return 1
    print("%d comparisons: %d differed, %d ours only, %d theirs only"
          % (compared, differed, ours_only, theirs_only))
    if differed or theirs_only:
        skew = oracle_version != version_tuple(version)
        if skew and not args.strict:
            print()
            print("The oracle is on UCD %s and the library on %s, so these need "
                  "triage by hand: DerivedAge filters codepoints that are new "
                  "and not property values that changed. Advisory, exit 0; for "
                  "an oracle on %s run"
                  % (unidata, version, version))
            print("  GHOTI_ORACLE_ALIAS=python=python-next make "
                  "check-oracle-unicodedata-strict")
            return 0
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
