#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-only
#
# Copyright (C) 2026 Corey Pennycuff
#
# This file is part of Ghoti.io Unicode.
#
# Ghoti.io Unicode is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License version 3 as
# published by the Free Software Foundation.
"""Differential: this library against CPython's unicodedata module.

A third opinion, and a genuinely independent one - CPython's tables are
generated by CPython's own tooling from the same files, which is exactly the
kind of second source worth having: it can agree with us and be wrong only if
the Consortium's data is wrong, and it disagrees the moment either of us has a
parsing bug.

**An oracle's Unicode version is the pin that matters, and it is rarely ours.**
CPython's `unicodedata` tracks the interpreter release - 3.13 carries UCD 15.1
where this library is on 17.0 - so a naive comparison reports every codepoint
added since as a disagreement. This script therefore compares only codepoints
whose `DerivedAge` is at most the oracle's version and **counts the rest as not
comparable rather than as agreement** (documentation/design.md section 12.4). A
run prints every number, because "12,000 agreed" means nothing without "and
4,000 could not be compared".

**And that filter is necessary and not sufficient**, which measuring it was the
only way to learn. `DerivedAge` says when a codepoint was *added*; it says
nothing about when its *properties changed*, and between 15.1 and 17.0 they
changed for codepoints that are decades old. U+0295 went from `Ll` to `Lo`,
U+1171E from `Mn` to `Mc` and from `NSM` to `L`, the mathematical nablas from
`L` to `ON`, U+226D became mirrored, and U+5146's numeric value went from a
million to a million million. Every one of those is the Consortium changing its
mind, and a differential two releases behind cannot tell that from a defect.

**The triage as it stands**, so that a reader does not re-derive it. Against
CPython 3.13.5 (UCD 15.1) and this library on 17.0, every difference is
accounted for and none of them is this library's:

  * `General_Category` 2, `Bidi_Class` 6, `East_Asian_Width` 188,
    `Bidi_Mirrored` 1, `Numeric_Value` 1: the Consortium changed its mind.
    U+0295 `Ll` to `Lo`; U+1171E `Mn` to `Mc` and `NSM` to `L`; the
    mathematical nablas `L` to `ON`; U+2630..U+2637, the trigrams, and 180 more
    symbols from `N` to `W`; U+226D newly mirrored; U+5146 a million to a
    million million. Each spot-checked against the 17.0 files rather than
    assumed - the first draft of this list claimed East_Asian_Width agreed
    everywhere, and it does not;
  * `Numeric_Value` 8 "ours only": cuneiform signs given values after 15.1;
  * `Name` 6,145 "ours only": the Tangut ideographs. CPython computes the CJK
    and Hangul algorithmic names and not these, which is the oracle's
    limitation and not a missing name;
  * `Decomposition_Type` over the Hangul syllables is skipped outright, for the
    same kind of reason: `unicodedata.decomposition()` returns the mapping
    `UnicodeData.txt` records, and a Hangul syllable's is arithmetic and
    recorded nowhere.

`Canonical_Combining_Class` agrees on all 289,460 comparable codepoints, and
every other property agrees on all but the handful above - which is the part
that would have caught a parsing bug, and is the reason to keep the script even
with a version skew it cannot filter.

So this is **advisory by default**: it reports and exits 0, because with a
version skew the disagreements are expected and the triage is a person's. Run
it with `--strict` where the oracle's UCD version matches the library's - which
is what the container images in `notes/suite/CONTAINERS.md` are for - and then
any disagreement is a defect and the exit status says so.

What is compared: General_Category, Canonical_Combining_Class, Bidi_Class,
East_Asian_Width, Bidi_Mirrored, Decomposition_Type, Numeric_Value and the
character names. Not the segmentation, normalisation or bidi algorithms:
`unicodedata` exposes none of them, and the Consortium's own conformance files
gate those in `make test`.

The library's answers come from the test binaries' dump modes -
`GUNI_SWEEP_DUMP` and `GUNI_NAME_DUMP` - rather than from a driver of its own,
because a differential wants the library's answers as text and a test binary
already links the library.

Usage:
    make test                                   # build the binaries first
    tools/oracle/unicodedata_diff.py
    tools/oracle/unicodedata_diff.py --property Bidi_Class

Exit status is 1 on any disagreement, and 1 if it could compare nothing.
"""

import argparse
import os
import subprocess
import sys
import unicodedata
from fractions import Fraction

MAX_CODEPOINT = 0x10FFFF

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))


def version_tuple(text):
    parts = [int(part) for part in text.split(".")]
    while len(parts) < 3:
        parts.append(0)
    return tuple(parts[:3])


def read_derived_age(ucd_dir):
    """Codepoint to the Unicode version that assigned it."""
    ages = [None] * (MAX_CODEPOINT + 1)
    with open(os.path.join(ucd_dir, "DerivedAge.txt"), encoding="utf-8") as handle:
        for line in handle:
            body = line.split("#", 1)[0].strip()
            if not body:
                continue
            first, _sep, value = (field.strip() for field in body.partition(";"))
            halves = first.split("..")
            low = int(halves[0], 16)
            high = int(halves[-1], 16)
            age = version_tuple(value)
            for cp in range(low, min(high, MAX_CODEPOINT) + 1):
                ages[cp] = age
    return ages


def read_value_aliases(ucd_dir):
    """{property: {long name: short name}}, for the codes unicodedata returns."""
    out = {}
    with open(os.path.join(ucd_dir, "PropertyValueAliases.txt"),
              encoding="utf-8") as handle:
        for line in handle:
            body = line.split("#", 1)[0].strip()
            if not body:
                continue
            fields = [field.strip() for field in body.split(";")]
            if fields[0] == "ccc":
                continue
            if len(fields) >= 3:
                out.setdefault(fields[0], {})[fields[2]] = fields[1]
    return out


def dump_property(binary, name):
    """The library's answer for one property, as (first, last, value) runs."""
    environment = dict(os.environ)
    environment["GUNI_SWEEP_DUMP"] = name
    environment.setdefault("GUNI_TEST_DATA", os.path.join(ROOT, "tests", "data"))
    result = subprocess.run([binary], env=environment, capture_output=True,
                            text=True, check=True)
    runs = []
    for line in result.stdout.splitlines():
        bounds, _space, value = line.partition(" ")
        low, _dots, high = bounds.partition("..")
        runs.append((int(low, 16), int(high, 16), value))
    return runs


def dump_names(binary):
    """The library's names, as {codepoint: name}."""
    environment = dict(os.environ)
    environment["GUNI_NAME_DUMP"] = "1"
    result = subprocess.run([binary], env=environment, capture_output=True,
                            text=True, check=True)
    out = {}
    for line in result.stdout.splitlines():
        code, _space, name = line.partition(" ")
        out[int(code, 16)] = name
    return out


class Comparison:
    """One property's tally, in four buckets.

    Four rather than two, because "disagreed" lumps together three different
    situations and only one of them is a defect:

      * **differed**: both sides have an answer and they are not the same. A
        defect, or the Consortium changing its mind between the two versions.
      * **ours only**: this library has an answer and the oracle has none. For
        names that is usually the oracle's limitation - CPython computes the CJK
        and Hangul algorithmic names and not the Tangut ones - and for a value
        it is usually newer data.
      * **theirs only**: the oracle has an answer and we do not, which is the
        one that would most likely be ours.
      * **not comparable**: the codepoint is newer than the oracle's UCD.
    """

    def __init__(self, name):
        self.name = name
        self.agreed = 0
        self.differed = 0
        self.ours_only = 0
        self.theirs_only = 0
        self.incomparable = 0
        self.examples = []

    def check(self, cp, ours, theirs):
        if ours == theirs:
            self.agreed += 1
            return
        if theirs is None:
            self.ours_only += 1
        elif ours is None:
            self.theirs_only += 1
        else:
            self.differed += 1
        if len(self.examples) < 4:
            self.examples.append((cp, ours, theirs))

    @property
    def compared(self):
        return self.agreed + self.differed + self.ours_only + self.theirs_only

    def report(self):
        status = "ok" if self.differed == 0 and self.theirs_only == 0 else "differs"
        print("  %-26s %8d agreed %6d differed %6d ours only %6d theirs only"
              "  %9d not comparable  %s"
              % (self.name, self.agreed, self.differed, self.ours_only,
                 self.theirs_only, self.incomparable, status))
        for cp, ours, theirs in self.examples:
            print("      U+%04X: ours %r, unicodedata %r" % (cp, ours, theirs))


def main(argv):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--build", default=os.path.join(ROOT, "build", "linux",
                                                        "release", "apps"),
                        help="where the test binaries are")
    parser.add_argument("--ucd", help="the unpacked UCD directory")
    parser.add_argument("--property", action="append",
                        help="compare only these (may be repeated)")
    parser.add_argument("--strict", action="store_true",
                        help="exit 1 on any disagreement, for an oracle whose "
                             "UCD version matches the library's")
    args = parser.parse_args(argv[1:])

    version = open(os.path.join(ROOT, "tools", "ucd", "UCD_VERSION"),
                   encoding="utf-8").read().strip()
    ucd_dir = args.ucd or os.path.join(ROOT, "third_party", "ucd", version)
    if not os.path.isdir(ucd_dir):
        raise SystemExit("%s does not exist; run tools/ucd/fetch.sh - this "
                         "differential needs DerivedAge.txt to know what is "
                         "comparable" % ucd_dir)

    sweep = os.path.join(args.build, "testSweep")
    names_binary = os.path.join(args.build, "testName")
    for binary in (sweep, names_binary):
        if not os.path.exists(binary):
            raise SystemExit("%s is not built; run make test first" % binary)

    oracle_version = version_tuple(unicodedata.unidata_version)
    print("oracle(host): CPython %s, unicodedata %s"
          % (sys.version.split()[0], unicodedata.unidata_version))
    print("library: UCD %s" % version)
    if oracle_version < version_tuple(version):
        print("the oracle is behind, so every codepoint assigned after %s is "
              "not comparable" % unicodedata.unidata_version)
    print()

    ages = read_derived_age(ucd_dir)
    aliases = read_value_aliases(ucd_dir)

    def comparable(cp):
        age = ages[cp]
        return age is not None and age <= oracle_version

    # (property, the key PropertyValueAliases uses, how to ask unicodedata)
    scalar = [
        ("General_Category", "gc", lambda ch: unicodedata.category(ch)),
        ("Bidi_Class", "bc", lambda ch: unicodedata.bidirectional(ch)),
        ("East_Asian_Width", "ea", lambda ch: unicodedata.east_asian_width(ch)),
    ]
    results = []
    wanted = args.property

    for name, key, ask in scalar:
        if wanted and name not in wanted:
            continue
        tally = Comparison(name)
        short_of = aliases.get(key, {})
        for low, high, value in dump_property(sweep, name):
            ours = short_of.get(value, value)
            for cp in range(low, high + 1):
                if not comparable(cp):
                    tally.incomparable += 1
                    continue
                theirs = ask(chr(cp))
                if theirs == "":
                    # unicodedata answers "" for a codepoint it has no data
                    # for, which is not a disagreement about the value.
                    tally.incomparable += 1
                    continue
                tally.check(cp, ours, theirs)
        results.append(tally)

    if not wanted or "Canonical_Combining_Class" in (wanted or []):
        tally = Comparison("Canonical_Combining_Class")
        for low, high, value in dump_property(sweep, "Canonical_Combining_Class"):
            ours = int(value)
            for cp in range(low, high + 1):
                if not comparable(cp):
                    tally.incomparable += 1
                    continue
                tally.check(cp, ours, unicodedata.combining(chr(cp)))
        results.append(tally)

    if not wanted or "Bidi_Mirrored" in (wanted or []):
        tally = Comparison("Bidi_Mirrored")
        for low, high, value in dump_property(sweep, "Bidi_Mirrored"):
            ours = value == "Yes"
            for cp in range(low, high + 1):
                if not comparable(cp):
                    tally.incomparable += 1
                    continue
                tally.check(cp, ours, bool(unicodedata.mirrored(chr(cp))))
        results.append(tally)

    if not wanted or "Decomposition_Type" in (wanted or []):
        tally = Comparison("Decomposition_Type")
        for low, high, value in dump_property(sweep, "Decomposition_Type"):
            # The long name, lowercased: unicodedata returns the UCD's own tag
            # text - "noBreak", "compat", "super" - and the long alias is that
            # text. Mapping to the short alias instead compared "nb" with
            # "nobreak" and reported every decomposable character.
            ours = value.lower()
            for cp in range(low, high + 1):
                if not comparable(cp):
                    tally.incomparable += 1
                    continue
                if 0xAC00 <= cp <= 0xD7A3:
                    # A documented limitation of the oracle rather than a
                    # difference: unicodedata.decomposition() returns the
                    # mapping UnicodeData.txt records, and a Hangul syllable's
                    # decomposition is arithmetic and is recorded nowhere. The
                    # UCD's own DerivedDecompositionType.txt says Canonical for
                    # all 11,172 of them, which is what this library says.
                    tally.incomparable += 1
                    continue
                text = unicodedata.decomposition(chr(cp))
                if not text:
                    theirs = "none"
                elif text.startswith("<"):
                    theirs = text[1:text.index(">")].lower()
                else:
                    # No tag means a canonical decomposition, and the long alias
                    # of that value is "Canonical". The first version of this
                    # said "can", the short alias, and reported all 13,233
                    # canonically decomposable characters as disagreements -
                    # which is what an oracle that is wrong looks like from the
                    # outside, and is why the triage is in this file.
                    theirs = "canonical"
                tally.check(cp, ours, theirs)
        results.append(tally)

    if not wanted or "Numeric_Value" in (wanted or []):
        tally = Comparison("Numeric_Value")
        for low, high, value in dump_property(sweep, "Numeric_Value"):
            ours = None if value == "None" else Fraction(value)
            for cp in range(low, high + 1):
                if not comparable(cp):
                    tally.incomparable += 1
                    continue
                try:
                    theirs = Fraction(unicodedata.numeric(chr(cp))).limit_denominator(
                        1000000)
                except ValueError:
                    theirs = None
                if ours is not None and theirs is not None:
                    # Compared as rationals, not as floats: the UCD has 1/3,
                    # and a float comparison of that is a coin toss.
                    tally.check(cp, ours, Fraction(theirs))
                else:
                    tally.check(cp, ours, theirs)
        results.append(tally)

    if not wanted or "Name" in (wanted or []):
        tally = Comparison("Name")
        ours_names = dump_names(names_binary)
        for cp in range(MAX_CODEPOINT + 1):
            if not comparable(cp):
                tally.incomparable += 1
                continue
            try:
                theirs = unicodedata.name(chr(cp))
            except ValueError:
                theirs = None
            ours = ours_names.get(cp)
            if ours is None and theirs is None:
                continue  # neither names it; nothing to compare
            tally.check(cp, ours, theirs)
        results.append(tally)

    for tally in results:
        tally.report()

    compared = sum(tally.compared for tally in results)
    differed = sum(tally.differed for tally in results)
    ours_only = sum(tally.ours_only for tally in results)
    theirs_only = sum(tally.theirs_only for tally in results)
    print()
    if compared == 0:
        print("nothing was compared, which is not a pass")
        return 1
    print("%d comparisons: %d differed, %d ours only, %d theirs only"
          % (compared, differed, ours_only, theirs_only))
    if differed or theirs_only:
        skew = oracle_version != version_tuple(version)
        if skew and not args.strict:
            print()
            print("The oracle is on UCD %s and the library on %s, so these need "
                  "triage by hand: DerivedAge filters codepoints that are new "
                  "and not property values that changed. Advisory, exit 0; run "
                  "with --strict against an oracle on %s."
                  % (unicodedata.unidata_version, version, version))
            return 0
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
